### ISSUE TITLE
Wrong caravan to deliver ordered stuff, faction declared war

### ISSUE THREAD

**Issue by Jan2607** [ToyWalrus/RequestItems#11]
I ordered stuff from a faction. One day later a caravan of said faction arrived. There was no notification that this caravan has the ordered items on it, but they had that special trade menu, so I got my ordered stuff. A few days later another caravan arrived and I got notified that this would be the ordered caravan. But they didn't have that trade menu. Because I couldn't fulfill the trade request with them, they got angry and declared war.

**Comment by ToyWalrus** [comment]
Should be fixed with recent mod update
